---

# usage: ansible-playbook <(curl http://sre.fahlke.io/ansible/zsh)

- name: "Z shell | Configure zsh"
  hosts: localhost
  vars:
    zsh_binary: '/usr/local/bin/zsh'

  tasks:
    - name: "Z shell | Add zsh to available shells"
      lineinfile:
         path: /etc/shells
         regexp: '^{{ zsh_binary }}'
         line: '{{ zsh_binary }}'
      become: true

    - name: "Z shell | Set zsh for the current user"
      command: "chsh -s {{ zsh_binary }} {{ ansible_env.USER }}"
      register: chsh_result
      become: true
      changed_when: "chsh_result.rc != 0"
