#!/bin/bash
set -euo pipefail

# define output colors
readonly COLOR_RED='\033[0;31m'
readonly COLOR_ORANGE='\033[0;33m'
readonly COLOR_GREEN='\033[0;32m'
readonly COLOR_RESET='\033[0m'

function __info_msg() {
  echo -e "${COLOR_GREEN}I:${COLOR_RESET} $1"
}

function __warning_msg() {
  echo -e "${COLOR_ORANGE}W:${COLOR_RESET} $1"
}

function __error_msg() {
  echo -e "${COLOR_RED}E:${COLOR_RESET} $1"
}

__info_msg "Creating symbolic links for the dotfiles (will overwrite any existing file)..."
ln -sfn $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
ln -sfn $HOME/.dotfiles/.gitignore $HOME/.gitignore
ln -sfn $HOME/.dotfiles/.zshrc     $HOME/.zshrc
ln -sfn $HOME/.dotfiles/.zshenv    $HOME/.zshenv
ln -sfn $HOME/.dotfiles/.zsh       $HOME/.zsh
